### ISSUE TITLE
Thanks for doing this! Also, why am I getting vastly different results from yesterday?

### ISSUE THREAD

**Issue by nicbentulan** [fsmosca/Rating-Correlations#1]
(I'm new to github.) Hello doesn't seem like any other way to contact you but thanks fsmosca! I shared this on reddit: https://www.reddit.com/r/chess/comments/sgkxfz/the_lichess_rating_correlation_web_app_is_done/

Edit: FYI it seems this username is available https://www.reddit.com/user/fsmosca

About the most recent update (which i guess i incorrectly posted there: https://github.com/streamlit/streamlit/issues/4348 )

Why am I getting vastly different results from yesterday? https://i.imgur.com/Sdu7Guj.png when i plug in these numbers i'm getting very different results. 1700 blitz meant 1548 chess960. Also 2000 bullet + 1400 blitz meant 1548 chess960 too. Now (still lichess) 1700 blitz means 1685 chess960 (https://i.imgur.com/5Tw1nrI.png) while 2000 bullet + 1400 blitz means 1756 chess960 (https://i.imgur.com/yIifJlF.png)

**Comment by fsmosca** [comment]
> Why am I getting vastly different results from yesterday? https://i.imgur.com/Sdu7Guj.png when i plug in these numbers i'm getting very different results. 1700 blitz meant 1548 chess960. Also 2000 bullet + 1400 blitz meant 1548 chess960 too. 

The formula to calculate it is in regression result.

![image](https://user-images.githubusercontent.com/22366935/152106567-4ad610c3-b0db-4942-a1c5-385912562411.png)

chess960_pred = bullet x 0.3118 + blitz x 0.3889 + 379.9 = 1547.96 or ~1548

>Now (still lichess) 1700 blitz means 1685 chess960 (https://i.imgur.com/5Tw1nrI.png) while 2000 bullet + 1400 blitz means 1756 chess960 (https://i.imgur.com/yIifJlF.png)

The last 2 images are weird, outlier margin widget is missing.

![2022-02-02 14_39_12-odd](https://user-images.githubusercontent.com/22366935/152106059-89761731-5653-4c76-bcc7-dd83f08f4b0a.png)

**Comment by nicbentulan** [comment]
thanks ! @fsmosca  

1 - (wait updated below. see next comment.) ok so i guess the formula changed but why? because more data was added?

2 - (wait updated below. see next comment.) i think outlier margin is missing because gofullpage doesn't scroll both sides.  now you can see it after scrolling manually on the left hand side and then gofullpage scrolls on the right hand side automatically https://imgur.com/a/MEmo2HW wait is outlier margin relevant to the rating prediction?

**Comment by nicbentulan** [comment]
1.1 - (update to 1) wait i tried again and [now the 3rd time](https://imgur.com/a/FMcx5rp) it's back to the same as [the 1st time](https://i.imgur.com/Sdu7Guj.png) like the exact same numbers. (for reference the 2nd time is: https://i.imgur.com/5Tw1nrI.png and https://i.imgur.com/yIifJlF.png) **what's up with that**?

i didn't record the regression formulas for 1st time or 2nd time but for 3rd time here's what i got:

blitz only:

chess960_pred = blitz x 0.6922 + 370.9294 = 1547.6694 or ~1548

bullet and blitz:

chess960_pred = bullet x 0.3118 + blitz x 0.3889 + 379.9057 = 1547.9657 or ~1548

i guess these may have been the same as for both [the 1st time](https://i.imgur.com/Sdu7Guj.png) and when you ran it but i guess it's different from when i ran the 2nd time...any idea why?

to clarify: the 2nd time i got (again i didn't record the regression formula):

2000 bullet + 1400 blitz = 1756 chess960

1700 blitz = 1685 chess960

soooo **what the 2nd time may have been different because the outlier margin was different?**

**Comment by nicbentulan** [comment]
ah lol i tried it myself i made outlier margin 50 and that's why i got different answers. ok thanks anyway. @fsmosca

**Comment by nicbentulan** [comment]
BUT in general if you were to add more data then  the formula will change right? @fsmosca

**Comment by fsmosca** [comment]
Correct.

Getting chess.com data is slow as the `live chess960` rating is not available in official api. I use the unofficial api instead which will terminate from time to time.

**Comment by nicbentulan** [comment]
ok thanks
