### ISSUE TITLE
Feature request: Cross-site? Eg input chessdotcom and output lichess and vice-versa

### ISSUE THREAD

**Issue by nicbentulan** [fsmosca/Rating-Correlations#2]
I figure like this pretty please? https://www.chessratingcomparison.com/

**Comment by fsmosca** [comment]
That is a great website.
 
I don't have the data to relate on different servers. I purely collected my data from lichess api and chess.com api. I will update the data from time to time.

To implement cross-site, at a minimum I just need a username in chess.com and a username in lichess.org of the same person. I will pick up its rating info through apis of both servers.

**Comment by nicbentulan** [comment]
oh yeah lol what was i thinking? anyway seems to be already done in https://www.reddit.com/r/chessmonitor/ or https://www.chessmonitor.com/
