### ISSUE TITLE
feature request: '2D histogram' or something

### ISSUE THREAD

**Issue by nicbentulan** [fsmosca/Rating-Correlations#3]
From reddit:

> Nice work, OP. One suggestion: I think a [2D histogram](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist2d.html) would show the data more clearly since there is a ton of overlap between points.

https://www.reddit.com/r/chess/comments/sgkxfz/the_lichess_rating_correlation_web_app_is_done/huy062q/

**Comment by fsmosca** [comment]
Added in https://github.com/fsmosca/Rating-Correlations/commit/6cfac90ab7a7eed6d73e067bd05bb33338324133 and deployed in [heroku](https://ratingcorrelations.herokuapp.com/)

![image](https://user-images.githubusercontent.com/22366935/152260708-238f30a6-591b-4bb3-b499-06ebd4bd9b20.png)

**Comment by nicbentulan** [comment]
cool thanks!

**Comment by nicbentulan** [comment]
wait response on reddit:

> That's a 1D histogram.

> 2D is a better way to plot a dense scatter plot since points overlap. https://stackoverflow.com/questions/42262563/please-explain-in-detail-2d-histogram-in-python

**Comment by fsmosca** [comment]
Left side is Lichess and right side is Chess.com. It is not yet published in heroku but already commited in repo.

![image](https://user-images.githubusercontent.com/22366935/152349151-3d11fcd7-f7be-4460-9c05-93ab3b0060c7.png)

**Comment by fsmosca** [comment]
2d hist is added in https://github.com/fsmosca/Rating-Correlations/commit/f7b226230587939735b26a58f9d7a65d959aa82b
This is also published in heroku.
