### ISSUE TITLE
dead link? huhuhu

### ISSUE THREAD

**Issue by nicbentulan** [fsmosca/Rating-Correlations#5]
hey ferdy!

1 - why change from herokuapp to streamlit?

2 - dead link?

https://rating-correlations.streamlit.app/

**Comment by fsmosca** [comment]
Try again, it should work now. There is payment now in heroku. Besides this is a streamlit app and this is now hosted in streamlit cloud. If there are issues, it can be easily sorted out.

**Comment by nicbentulan** [comment]
hooray thanks! :D
